package com.app.spotifyclone.model

var titles = arrayOf(

    "",
    "As 50 mais tocadas no Brasil",
    "As 50 mais tocadas no mundo",
    "As 50 mais tocadas na Argentina",
    "As 50 mais tocadas na Espanha",
    "As 50 mais tocadas do Spotify",
    "As 50 mais tocadas no Peru",
    "As 50 mais tocadas no mundo inteiro",
    "Today's Top Hits",
    "Rock Classics",
    "This is Marília Mendonça",
    "Gusttavo Lima",
    "RAPública",
    "Funk Hits",
    "Sucessos Gospel",
    "Pagodeira",
    "Esquenta Sertanejo",
    "Mood Booster",
    "Young, Wild & Free",
    "Confidence Boost",
    "Heart Beats",
    "Alone Again",
    "Hits Felizes",
    "Good Vibes",
    "Verão Forever",
    "Cafezinho",
    "Calm Down",
    "Cantando no Chuveiro",
    "Hora Acústica",
    "Lo-Fi Beats",
    "Treino Anos 80",
    "Jantar Relax",
    "Coffee Table Jazz"
)